---
apiVersion: v1
kind: Service
metadata:
  name: twirpt
  labels:
    app: twirpt
spec:
  type: NodePort
  selector:
    app: twirpt
  ports:
  - port: 8080
    nodePort: 30000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twirpt
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: twirpt
    spec:
      containers:
      - name: twirpt
        image: twirpt
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: "PORT"
            value: "8080"
